-- MySQL Script generated by MySQL Workbench
-- sø. 02. april 2017 kl. 19.23 +0200
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gridwalking
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gridwalking
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gridwalking` DEFAULT CHARACTER SET utf8 COLLATE utf8_danish_ci ;
USE `gridwalking` ;

-- -----------------------------------------------------
-- Table `gridwalking`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gridwalking`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `guid` VARCHAR(36) NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  `score` INT UNSIGNED NOT NULL,
  `l13` INT UNSIGNED NOT NULL,
  `l12` INT UNSIGNED NOT NULL,
  `l11` INT UNSIGNED NOT NULL,
  `l10` INT UNSIGNED NOT NULL,
  `l9` INT UNSIGNED NOT NULL,
  `l8` INT UNSIGNED NOT NULL,
  `l7` INT UNSIGNED NOT NULL,
  `l6` INT UNSIGNED NOT NULL,
  `l5` INT UNSIGNED NOT NULL,
  `l4` INT UNSIGNED NOT NULL,
  `l3` INT UNSIGNED NOT NULL,
  `l2` INT UNSIGNED NOT NULL,
  `l1` INT UNSIGNED NOT NULL,
  `l0` INT UNSIGNED NOT NULL,
  `bonus` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `score_idx` (`score` ASC),
  UNIQUE INDEX `guid_UNIQUE` (`guid` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_danish_ci;


-- -----------------------------------------------------
-- Table `gridwalking`.`grid`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gridwalking`.`grid` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `owner` INT UNSIGNED NOT NULL,
  `level` INT UNSIGNED NOT NULL,
  `grid` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_grid_user1_idx` (`owner` ASC),
  UNIQUE INDEX `owner_grid_UNIQUE` (`owner` ASC, `grid` ASC))
  CONSTRAINT `fk_grid_user`
    FOREIGN KEY (`owner`)
    REFERENCES `gridwalking`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
