-- MySQL Script generated by MySQL Workbench
-- lø. 24. des. 2016 kl. 09.02 +0100
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gridwalking
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gridwalking
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gridwalking` DEFAULT CHARACTER SET utf8 COLLATE utf8_danish_ci ;
USE `gridwalking` ;

-- -----------------------------------------------------
-- Table `gridwalking`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gridwalking`.`user` (
  `id` VARCHAR(36) NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  `score` INT UNSIGNED NOT NULL,
  `l13` INT UNSIGNED NOT NULL,
  `l12` INT UNSIGNED NOT NULL,
  `l11` INT UNSIGNED NOT NULL,
  `l10` INT UNSIGNED NOT NULL,
  `l9` INT UNSIGNED NOT NULL,
  `l8` INT UNSIGNED NOT NULL,
  `l7` INT UNSIGNED NOT NULL,
  `l6` INT UNSIGNED NOT NULL,
  `l5` INT UNSIGNED NOT NULL,
  `l4` INT UNSIGNED NOT NULL,
  `l3` INT UNSIGNED NOT NULL,
  `l2` INT UNSIGNED NOT NULL,
  `l1` INT UNSIGNED NOT NULL,
  `l0` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `score_idx` (`score` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_danish_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
