#!/bin/bash
#

if [ "$1" = "autoconf" ]; then
	echo yes 
	exit 0
fi

if [ "$1" = "config" ]; then

	echo 'graph_title Grid Walking highscore list'
	echo 'graph_args --base 1000 -l 0'
	echo 'graph_scale no'
	echo 'graph_vlabel score'
	echo 'graph_category apps'
        echo 'graph_info Grid Walking highscore list'
	echo 'score0.label #1'
	echo 'score0.draw LINE2'
        echo 'score0.info #1'
	echo 'score1.label #2'
	echo 'score1.draw LINE2'
        echo 'score1.info #1'
	echo 'score2.label #3'
	echo 'score2.draw LINE2'
        echo 'score2.info #1'
	echo 'score3.label #4'
	echo 'score3.draw LINE2'
        echo 'score3.info #1'
	echo 'score4.label #5'
	echo 'score4.draw LINE2'
        echo 'score4.info #1'
	echo 'score5.label #6'
	echo 'score5.draw LINE2'
        echo 'score5.info #1'
	echo 'score6.label #7'
	echo 'score6.draw LINE2'
        echo 'score6.info #1'
	echo 'score7.label #8'
	echo 'score7.draw LINE2'
        echo 'score7.info #1'
	echo 'score8.label #9'
	echo 'score8.draw LINE2'
        echo 'score8.info #1'
	echo 'score9.label #10'
	echo 'score9.draw LINE2'
        echo 'score9.info #1'
	exit 0
fi

scorefile="/tmp/gridwalking.score"
mysql -u gridwalking -p<password> -D gridwalking -B -N -e "SELECT score FROM user ORDER BY score DESC LIMIT 10" > $scorefile
i=0
while read -r line
do
 echo "score$i.value $line"
 ((i++))
done <$scorefile
